In [1]:
import numpy as np

In [2]:
ar_1 = np.array([3, 5, 4])
print(ar_1)

[3 5 4]


In [3]:
mat = np.array([[5, 4, 2], [2, 3, 5], [1, 2, 3]])
print(mat)

[[5 4 2]
 [2 3 5]
 [1 2 3]]


In [4]:
ar_1.shape

(3,)

In [5]:
mat.shape

(3, 3)

In [6]:
len(mat.shape)

2

In [7]:
zero = np.zeros((3, 3, 3))
print(zero)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
z = np.zeros((4, 2))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
o = np.ones(shape=(2, 5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
a = np.array([1, .5, 3])
print(a)

[1.  0.5 3. ]


In [11]:
e = np.empty((3, 3))
print(e)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 9.387e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [12]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
diagonale = np.diag(i)
print(diagonale)

[1. 1. 1.]


In [14]:
np.diag(diagonale)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
i[0]

array([1., 0., 0.])

In [16]:
i[0][0]

1.0

In [17]:
print(mat[0])
print(mat[0][0])

[5 4 2]
5


In [18]:
a = np.array([5, 3])
b = np.array([2, 4])
print(a + b)
print(a - b)

[7 7]
[ 3 -1]


In [19]:
c = a * b
print(c)
print(a / b)

[10 12]
[2.5  0.75]


In [20]:
a.dot(b)

22

In [21]:
print(mat)
print(mat.sum(axis=0))

[[5 4 2]
 [2 3 5]
 [1 2 3]]
[ 8  9 10]


In [22]:
print(np.sort(mat))
print(np.sort(mat, axis=0))

[[2 4 5]
 [2 3 5]
 [1 2 3]]
[[1 2 2]
 [2 3 3]
 [5 4 5]]


In [23]:
a = np.array([3, 3, 5])
b = np.array([4, 2, 3])
print(np.concatenate((a, b)))
# print(np.concatenate((a, b), axis=1)) # errore! non esiste asse 1

[3 3 5 4 2 3]


In [24]:
print(a.shape)

a = np.array([[3, 3, 5]])
b = np.array([[4, 2, 3]])

print(np.concatenate((a, b), axis=1))
a.shape

(3,)
[[3 3 5 4 2 3]]


(1, 3)

In [25]:
print(a)
np.insert(a, 2, 0) # agisce su una copia, bisognerebbe sovrascrivere per avere il cambiamento
a = np.insert(a, 2, 0)

[[3 3 5]]


In [26]:
print(np.delete(a, 2))
a

[3 3 5]


array([3, 3, 0, 5])

In [27]:

a.reshape(2, 2)
print(a)

[3 3 0 5]


In [28]:
a = a.reshape(2, 2)
print(a)

[[3 3]
 [0 5]]


In [29]:
b = a.flatten()
print(b)
print(a)

[3 3 0 5]
[[3 3]
 [0 5]]


In [30]:
a.ravel()

array([3, 3, 0, 5])

In [31]:
a

array([[3, 3],
       [0, 5]])