Importiamo `numpy`

In [1]:
import numpy as np

Per calcolare la **trasposta** di una matrice, usiamo la funzione `transpose()`.

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

Per calcolare l'**inversa** di una matrice, usiamo la funzione `inv()` del package `linalg`

In [3]:
x = np.array([[5, 0, 0], [0, 2, 0], [0, 0, 4]])
np.linalg.inv(x)

array([[0.2 , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

Se proviamo a calcolare l'inversa di una matrice rettangolare o di una matrice singolare, la funzione `inv()` restituirà un `LinAlgError`.

In [4]:
# con matrice rettangolare:
try:
    mat = np.array([[1,2,3], [4,5,6]])
    np.linalg.inv(mat)
except np.linalg.LinAlgError:
    print("Error: matrix is a rectangular matrix")

# con matrice singolare
try:
    mat = np.array([[1,1,1],[2,2,2],[0,0,1]])
    np.linalg.inv(mat)
except np.linalg.LinAlgError:
    print("Error: matrix is a singular matrix")

Error: matrix is a rectangular matrix
Error: matrix is a singular matrix


Usiamo la funzione `inner()` per calcolare il prodotto **scalare** tra due vettori. Partiamo con un caso monodimensionale:



In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.inner(a, b)

32

Vediamo cosa accade in un caso multidimensionale:

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 1], [1, 0]])

np.inner(a, b)

array([[2, 1],
       [4, 3]])

In questo caso, la formulazione è del tipo:
$$
p = \begin{bmatrix}
        a_1 \cdot b_1 + a_2 \cdot b_2 & a_1 \cdot b_3 + a_2 \cdot b_4 \\
        a_3 \cdot b_1 + a_4 \cdot b_2 & a_3 \cdot b_3 + a_4 \cdot b_4
    \end{bmatrix}
  = \begin{bmatrix}
        1 \cdot 0 + 2 \cdot 1 & 1 \cdot 1 + 2 \cdot 0 \\
        3 \cdot 0 + 4 \cdot 1 & 3 \cdot 1 + 4 \cdot 0
    \end{bmatrix}
  = \begin{bmatrix}
        2 & 1 \\
        4 & 3
    \end{bmatrix}
$$

Il prodotto **esterno** viene calcolato mediante la funzione `outer()`:

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])

np.outer(a, b)

array([[3, 4],
       [6, 8]])

La funzione `matmul()` ci permette di effettuare il prodotto matriciale tra due matrici.

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.matmul(a, b)

array([[19, 22],
       [43, 50]])

Per elevare la **matrice a potenza** utilizzare la funzione `matrix_power()` del package `linalg`:

In [9]:
np.linalg.matrix_power(a, 5)

array([[1069, 1558],
       [2337, 3406]])

Per effettuare la **decomposizione ai valori singolari** (SVD):

In [10]:
(u, s, v) = np.linalg.svd(a)
print(f"u:\n{u}\ns:\n{s}\nv:\n{v}")

u:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
s:
[5.4649857  0.36596619]
v:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


Per calcolare autovettori ed autovalori di una matrice, usiamo la funzione `eig()` del package `linalg`:

In [11]:
(w, v) = np.linalg.eig(a)
print(f"Autovalori:\n{w}\nAutovettori:\n{v}")

Autovalori:
[-0.37228132  5.37228132]
Autovettori:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Per calcolare la norma, usiamo la funzione `norm()`:

In [12]:
np.linalg.norm(a)

5.477225575051661

Per calcolare rango, determinante e traccia, usiamo rispettivamente `matrix_rank()`, `det()`, `trace()`:

In [13]:

rank = np.linalg.matrix_rank(a)
det = np.linalg.det(a)
trace = np.trace(a)

print(f"Rango: {rank}\nDeterminante: {det}\nTraccia: {trace}")

Rango: 2
Determinante: -2.0000000000000004
Traccia: 5


Per risolvere il seguente sistema di equazioni lineari:
$$
\begin{cases}
    x + 2\bar{x} + 5\overline{\overline{x}} = y   \\
    2x + 2\bar{x} + 3\overline{\overline{x}} = 3y \\
    2x + 2\bar{x} + \overline{\overline{x}} = 2y
\end{cases}
$$

In [14]:
x = np.array([[1, 2, 2], [2, 2, 2], [5, 3, 1]])
y = np.array([1, 3, 2])

np.linalg.solve(x, y)

array([ 2.  , -3.75,  3.25])